name: build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Cache Go build
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -race -count=1 ./...
      - name: Coverage (optional)
        if: success()
        run: |
          if [ "${COVERAGE}" = "1" ]; then
            go test -coverprofile=coverage.out ./...
            go tool cover -func=coverage.out | tail -n 1
          else
            echo "Skipping coverage (set COVERAGE=1 to enable)"
          fi
