name: semantic-release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
          check-latest: true
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          install-only: true
      - name: Install dependencies and plugins without modifying lockfile
        run: |
          # Use --no-save to prevent lockfile changes
          npm ci --prefer-offline --no-audit --no-fund
          npm install --no-save @semantic-release/exec
      - name: Verify clean working directory
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Working directory is dirty:"
            git status --porcelain
            echo "Cleaning up..."
            git checkout -- .
            git clean -fd
          fi
          echo "Working directory is now clean"
      - name: Delete existing release assets to prevent conflicts
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            try {
              // Get all releases to find any existing ones
              const releases = await github.rest.repos.listReleases({ owner, repo, per_page: 10 });
              for (const release of releases.data) {
                if (release.tag_name.startsWith('v1.') || release.tag_name.includes('untagged')) {
                  console.log(`Cleaning assets from release: ${release.tag_name}`);
                  for (const asset of release.assets) {
                    console.log(`Deleting asset: ${asset.name}`);
                    await github.rest.repos.deleteReleaseAsset({ 
                      owner, 
                      repo, 
                      asset_id: asset.id 
                    });
                  }
                }
              }
            } catch (e) {
              console.log('No releases or assets to delete:', e.message);
            }
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
